from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('pro_home', views.pro_home, name='pro_home'),
    path('user-profile', views.user_prof, name='user_prof'),
    path('user-properties/', views.properties_page, name='properties_page'),
    path('property-details/<property_id>',
         views.property_details_page, name='property_details'),
    path('edit-property-page/<property_id>',
         views.edit_property_page, name='edit_property_page'),
    path('complaints', views.complaints,
         name='complaints'),
    path('voilations/', views.voilations,
         name='voilations'),
    path('property-search', views.property_search_page,
         name='property_search_page'),
    path('user-is-pro', views.already_pro, name='pro_user'),
    path('forgot-password/', views.ForgetPassword, name="forget_password"),
    path('password-reset-verification/<auth_token>/',
         views.ChangePassword, name="change_password"),
    path('login-attempt', views.login_attempt, name='login'),
    path('verify/<auth_token>', views.verify, name='verify'),
    path('logout-attempt', views.logout_attempt, name='logout'),
    path('register-attempt', views.register, name='register'),
    path('edit-user-information', views.edit_user_information,
         name='edit_user_information'),
    path('update-profile-info', views.update_profile_info,
         name='update_profile_info'),
    path('update-profile-image', views.change_profile_image,
         name='change_profile_image'),
    path('update-password', views.update_password_info,
         name='update_password_info'),
    path('update-subscription', views.update_subscription,
         name='update_subscription'),
    path('my_webhook', views.stripe_webhook),
    path('pricing', views.princing, name='price'),
    path('adding-property', views.add_property, name='addproperty'),
    path('edit-property/<property_id>',
         views.edit_property, name='edit_property'),
    path('edit-contact/<int:contact_id>',
         views.edit_contact, name='edit_contact'),
    path('add-property', views.add_properties,
         name='add_property'),
    path('delete_street_property/<int:pro_id>',
         views.delete_street_property, name='delete_street_property'),
    path('membership-process', views.become_pro, name='pro'),
    path('choose-package/<param1>', views.payment_after_registeration,
         name='payment_after_registeration'),
    path('paying', views.payment_at_registration,
         name='payment_at_registration'),
    path('verify-email', views.verify_email, name='verify_email'),
    path('update-subscription', views.change_subscription,
         name='change_subscription'),
    path('success/paid', views.success_second, name='success_2'),
    path('success/payment/done', views.success_third, name='success_3'),
    path('success', views.success, name='success'),
    path('cancel', views.cancel, name='cancel'),
    path('twenty-plus-properties', views.twenty_plus, name='twenty_plus'),
    path('contact-us', views.contact, name='contact'),
    path('contacting', views.contact_process, name="contacting"),
]


# from django.urls import path
# from . import views
# urlpatterns = [
#     path('', views.home, name='home'),
#     path('pro_home', views.pro_home, name='pro_home'),


#     path('user-properties/', views.properties_page, name='properties_page'),
#     path('property-details/<property_id>',
#          views.property_details_page, name='property_details'),
#     path('edit-property-page/<property_id>',
#          views.edit_property_page, name='edit_property_page'),

#     path('complaints', views.complaints,
#          name='complaints'),
#     path('voilations/', views.voilations,
#          name='voilations'),
#     path('property-search', views.property_search_page,
#          name='property_search_page'),

#     path('update-subscription', views.change_subscription,
#          name='change_subscription'),


#     path('user-is-pro', views.already_pro, name='pro_user'),
#     path('forgot-password/', views.ForgetPassword, name="forget_password"),
#     path('password-reset-verification/<auth_token>/',
#          views.ChangePassword, name="change_password"),

#     path('login-attempt', views.login_attempt, name='login'),
#     path('verify/<auth_token>', views.verify, name='verify'),
#     path('logout-attempt', views.logout_attempt, name='logout'),
#     path('register-attempt', views.register, name='register'),

#     path('edit-user-information', views.edit_user_information,
#          name='edit_user_information'),
#     path('update-profile-info', views.update_profile_info,
#          name='update_profile_info'),
#     path('update-password', views.update_password_info,
#          name='update_password_info'),
#     path('update-subscription', views.update_subscription,
#          name='update_subscription'),

#     path('my_webhook', views.stripe_webhook),
#     path('pricing', views.princing, name='price'),
#     path('adding-property', views.add_property, name='addproperty'),
#     path('edit-property/<property_id>',
#          views.edit_property, name='edit_property'),
#     path('edit-contact/<int:contact_id>',
#          views.edit_contact, name='edit_contact'),
#     path('add-property', views.add_properties,
#          name='add_property'),
#     path('delete_street_property/<int:pro_id>',
#          views.delete_street_property, name='delete_street_property'),

#     path('choose-package/<param1>', views.payment_after_registeration,
#          name='payment_after_registeration'),
#     path('paying', views.payment_at_registration,
#          name='payment_at_registration'),
#     path('verify-email', views.verify_email, name='verify_email'),


#     path('membership-process', views.become_pro, name='pro'),
#     path('success/paid', views.success_second, name='success_2'),

#     path('success/payment/done', views.success_third, name='success_3'),
#     path('success', views.success, name='success'),
#     path('cancel', views.cancel, name='cancel'),
#     path('twenty-plus-properties', views.twenty_plus, name='twenty_plus'),
#     path('contact-us', views.contact, name='contact'),
#     path('contacting', views.contact_process, name="contacting"),
# ]
