# Generated by Django 4.1.4 on 2023-01-21 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_address_property_house_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='complaint_assignment',
            new_name='complaint_adress',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='complaint_priority',
            new_name='complaint_status',
        ),
        migrations.AddField(
            model_name='complaints',
            name='complaint_deposition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='complaint_inspection_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voilation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voilations', to=settings.AUTH_USER_MODEL),
        ),
    ]
