# Generated by Django 4.1.4 on 2023-01-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_complaint_assignment_complaints_complaint_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voilation',
            name='v_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
