# Generated by Django 4.1.4 on 2023-02-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_property_email_remove_property_email1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='strip_subscription_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
